config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resource :admin, only: [:show, :edit, :update]
  resources :dishes
  resources :orders, only: [:show, :index, :create]
  get "/cart", to: "orders#show"
  resources :order_dishes, only: [:create, :update, :destroy]
  resources :tables
  resources :guests
  resources :order_combos, only: [:create, :update, :destroy]
  resources :combos, only: [:index, :show]
  namespace :admin do
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :combos do
      resources :dishes
    end
    resources :orders do
      resources :order_dishes
      resources :order_combos
    end
    resources :discount_codes
    resources :users
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include Encode
  belongs_to :guest
  belongs_to :table, inverse_of: :orders
  delegate :capacity, to: :table

  has_many :order_dishes
  has_many :order_combos

  after_save :generate_code

  accepts_nested_attributes_for :guest
  accepts_nested_attributes_for :table

  def subtotal
    total_dishes_price = order_dishes.map{|order_dish| order_dish.valid? ?
      (order_dish.quantity * order_dish.price) : 0}.sum
    total_combos_price = order_combos.map{|order_combo| order_combo.valid? ?
      (order_combo.quantity * order_combo.price) : 0}.sum
    total_dishes_price + total_combos_price
  end

  def original_price
    total_dishes_price = order_dishes.map{|order_dish| order_dish.valid? ?
      (order_dish.quantity * order_dish.price) : 0}.sum
    total_combos_price = order_combos.map{|order_combo| order_combo.valid? ?
      (order_combo.quantity * order_combo.original_price) : 0}.sum
    total_dishes_price + total_combos_price
  end
end

app/models/supports/order.rb
class Supports::Order
  attr_reader :orders

  def initialize arg
    @orders = arg
  end

  def orders
    @orders[:order]
  end

  def orders_search
    search.result.page(@orders[:param][:page]).per_page Settings.max_result
  end

  def search
    search = Order.ransack @orders[:param][:q]
    search.sorts = %w(code) if search.sorts.empty?
    search
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :logged_in_admin
  before_action :check_for_cancel

  load_and_authorize_resource

  def index
    @orders_support = Supports::Order.new order: Order.all, param: params
    @tables = Table.all
  end

  def show
    @support = Supports::Order.new discount: params[:discount]
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new order_params
    if @order.save
      flash[:success] = t "flash.order.create_success"
      redirect_to admin_order_path @order
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update_attributes order_params
      flash[:success] = t "flash.order.update_success"
      redirect_to admin_orders_path
    else
      render :edit
    end
  end

  def destroy
    if @order.destroy
      flash[:success] = t "flash.order.delete_success"
    else
      flash[:danger] = t "flash.order.delete_fail"
    end
    respond_to do |format|
      format.html{redirect_to :back}
      format.json{head :no_content}
    end
  end

  private
  def order_params
    params.require(:order).permit :code, :discount, :day, :time_in, :is_confirm,
      guest_attributes: [:id, :name], table_attributes: [:id, :capacity]
  end

  def check_for_cancel
    redirect_to admin_orders_path if params[:commit] == %w(Cancel)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    info = params[:order]
    if info
      order = Order.find_by code: info[:code]
      if order && order.guest.email == info[:email]
        session[:order_id] = order.id
        flash[:success] = t "flash.order.find_order"
        redirect_to cart_path
      else
        flash[:danger] = t "flash.order.cant_find_order"
        redirect_to orders_path
      end
    end
  end

  def show
    order_dish = current_order.order_dishes
    @order_dishes =
      if order_dish.blank?
        nil
      else
        order_dish
      end
    @order_combos = current_order.order_combos
    @order_dishes = nil if @order_dishes.blank?
  end

  def create
    params[:guest_id] = session[:guest]["id"]
    if current_order.table_id
      session.delete :order_id if current_order.code.present?
      redirect_to cart_path
    else
      @order = current_order
      @order.save
      session[:order_id] = @order.id
      @order.update_attributes order_params
      flash[:success] = t "flash.order.create_success"
      UserCreateOrderNotifierMailer.send_email(@order).deliver
      render json: {path: cart_path}
    end
  end

  private
  def order_params
    params.permit :table_id, :day, :time_in, :guest_id
  end

  def find_guest code
    @guest = Guest.find_by code: code
  end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
  def find_discount param
    if param
      discount = DiscountCode.find_by code: param
      if discount
        discount
      else
        true
      end
    end
  end
end

app/views/admin/orders/_add_order_item.html.erb
<div>
  <div>
    <div class="choose-code-btn discount-result">
      <p class="text-background">
        <%= t "discount.choose_code" %>
      </p>
    </div>
  </div>
</div>

app/views/admin/orders/_discount_row.html.erb
<div id="discount-render">
  <div id="discount-row">
    <% if find_discount(params[:discount]).present? %>
      <% if find_discount(params[:discount]) == true %>
        <p class="discount-result">
          <%= t "discount.reenter" %>
        </p>
      <% elsif find_discount(params[:discount]).status == 2 %>
        <p class="discount-result">
          <%= t "discount.used_code" %>
        </p>
      <% elsif find_discount(params[:discount]).status == 1 %>
        <p class="discount-result" id="code-true">
          <%= t "discount.discount" %>
          <strong><%= find_discount(params[:discount]).discount %></strong>
          <%= t "discount.discount2" %>
        </p>
        <div id="choose-code" class="choose-code-btn discount-result">
          <p class="text-background">
            <%= t "discount.choose_code" %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, order] do |f| %>
  <%= f.label :code, t(".code"), class:"form-label-3" %>
  <%= f.text_field :code, class: "form-control" %>

  <%= f.fields_for :guest do |guest| %>
    <%= guest.label :name, t(".guest_name"), class:"form-label-3" %>
    <%= guest.text_field :name, class: "form-control" %>
  <% end %>

  <%= f.fields_for :table do |table| %>
    <%= table.label :capacity, t(".capacity"), class:"form-label-3" %>
    <%= table.text_field :capacity, class: "form-control" %>
  <% end %>

  <%= f.label :discount, t(".discount"), class:"form-label-3" %>
  <%= f.number_field :discount, class: "form-control", min: 0  %>

  <%= f.label :date, t(".date"), class:"form-label-3" %><br>
  <%= f.text_field :day, class: "form-control datepicker" %><br>

  <%= f.label :time_in, t(".time_in"), class:"form-label-3" %><br>
  <%= f.select :time_in,[[t("select.em"), 1], [t("select.lm"), 2],
    [t("select.ea"), 3], [t("select.la"), 4],
    [t("select.ee"), 5], [t("select.le"), 6]],
    {include_blank: t("reserve.time")}, id:"time_field",
    class: "form-control", required: true %>
  <br>

  <%= f.label :is_confirm, t(".status"), class:"form-label-3" %>
  <%= f.radio_button :is_confirm, "true", checked: true %> <%= t(".approved") %>
  <%= f.radio_button :is_confirm, "false" %> <%= t(".canceled") %>

  <br><br><br>
  <%= f.submit t("button.clear"), type: :reset,
    class: "btn btn-danger pull-right" %>
  <%= f.submit class: "btn btn-primary pull-right" %>
<% end %>

app/views/admin/orders/_modal.html.erb
<div id="myModal2" class="modal">
  <div class="modal-content modal-sm">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2 class="text-center"><%= t "admin_order.input_code" %></h2>
    </div>
    <div class="modal-body">
      <div class="row row-padding">
        <div class="col-sm-8 text-center modal-part modal-left">
          <p class="discount-code-input">
            <%= t "admin_order.discount_code" %></p>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <input placeholder="<%= t "admin_order.your_code" %>"
                class="input-form form-control" id="discount-code-input">
              </input>
            </div>
          </div>
        </div>
        <div class="col-sm-4 text-center modal-part modal-left">
          <div class="btn-check">
            <i id="check-discount-code" class="fa fa-paper-plane"></i>
          </div>
        </div>
      </div>
      <%= render "discount_row", discount: discount %>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>

app/views/admin/orders/_modal_save_order.html.erb
<div id="save-order-modal" class="modal">
  <div class="modal-content modal-sm">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2 class="text-center"><%= t "admin_order.input_code" %></h2>
    </div>
    <div class="modal-body">
      <%= render "add_order_item" %>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>

app/views/admin/orders/_order.html.erb
<%= search_form_for [:admin, order.search], remote: true, method: :get do |f| %>
  <div class="apple-pagination">
    <%= paginate order.orders_search, remote: true %>
  </div>
  <br>
  <div class="b10">
    <%= f.text_field :code_cont, class:"pj-form-field pj-form-field-search w350",
      placeholder: t("admin_order.search_by_code") %>
    <div class="float_right t5">
      <%= link_to t(".all"), {q: nil, remote: true},
        class:"pj-button btn-all"%>
      <%= link_to t("admin_order.confirmed"), {q: {is_confirm_eq: true}, remote: true},
        class:"pj-button btn-all" %>
      <%= link_to t("admin.orders.form.canceled"), {q: {is_confirm_eq: false}, remote: true},
        class:"pj-button btn-all" %>
    </div>
  </div>
  <div class="pj-form-filter-advanced col-sm-12">
    <span class="pj-menu-list-arrow"></span>
    <div class="pj-form pj-form-search">
      <div class="w350">
        <p>
          <%= f.label :date_from, class: "date" %>
          <%= f.text_field :day_gteq,
            class: "datepicker pj-form-field pointer w150 f-text f-calendar" %>
        </p>
        <p>
          <%= f.label :date_to, class: "date" %>
          <%= f.text_field :day_lteq,
            class: "datepicker pj-form-field pointer w150 f-text f-calendar" %>
        </p>
      </div>
      <div class="w350">
        <p>
          <%= f.label :table_id, class: "title" %>
          <span class="inline-block">
            <%= f.collection_select :table_id_eq, tables, "id", "id",
              {include_blank: t(".choose")},
              {class: "btn btn-default pj-form-field w180"} %>
          </span>
        </p>
        <p>
          <%= f.label :name, class: "title" %>
          <span class="inline-block">
            <%= f.text_field :guest_name_cont,
              class: "pj-form-field w180" %>
          </span>
        </p>
        <p>
          <label class="title">&nbsp;</label>
          <%= f.submit  t(".search"), class: "pj-button" %>
          <%= link_to t("admin_order.cancel"), {remote: true}, class: "pj-button",
            id: "clear" %>
        </p>
      </div>
      <div class="w350">
        <p>
          <%= f.label :phone, class: "title" %>
          <span class="inline-block">
            <%= f.text_field :guest_phone_num_cont,
              class: "pj-form-field w180" %>
          </span>
        </p>
        <p>
          <%= f.label :email, class: "title" %>
          <span class="inline-block">
            <%= f.text_field :guest_email_cont,
              class: "pj-form-field w180" %>
          </span>
        </p>
      </div>
      <br class="clear_both">
    </div>
  </div>
  <div class="apple-pagination">
    <%= paginate order.orders_search, remote: true %>
  </div>
  <br>
  <table class="table-order table">
    <thead>
      <tr>
        <th class="left width-90">
          <%= sort_link order.search, :code, t(".code"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="left width-170">
          <%= sort_link order.search, :date, t(".date"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="left width-110"><%= t "admin.orders.form.time" %></th>
        <th class="left width-170">
          <%= sort_link order.search, :guest_name, t(".guest_name"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="text-center width-90"><%= t ".table" %></th>
        <th class="text-center width-90">
          <%= sort_link order.search, :table_capacity, t(".capacity"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="text-center width-90">
          <%= sort_link order.search, :discount, t(".discount"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="text-center width-90 text-center">
          <%= t ".status" %>
        </th>
        <th class="actions" colspan="2"><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody>
      <% if order.orders_search.any? %>
        <% order.orders_search.each do |order| %>
          <% if order.day %>
            <tr>
              <td><%= link_to order.code, admin_order_path(order) %></td>
              <td><%= order.day.in_time_zone(
                Settings.time_zone).strftime('%b %d %Y') %></td>
              <td>
                <% if order.time_in == 1 %><%= t "select.em" %><% end %>
                <% if order.time_in == 2 %><%= t "select.lm" %><% end %>
                <% if order.time_in == 3 %><%= t "select.ea" %><% end %>
                <% if order.time_in == 4 %><%= t "select.la" %><% end %>
                <% if order.time_in == 5 %><%= t "select.ee" %><% end %>
                <% if order.time_in == 6 %><%= t "select.la" %><% end %>
              </td>
              <td><%= order.guest.name %></td>
              <td class="text-center"><%= order.table_id %></td>
              <td class="text-center"><%= order.capacity %></td>
              <td class="text-center"><%= order.discount %>
                <i class="fa fa-percent"></i></td>
              <td class="text-center">
                <% if order.is_confirm? %>
                  <span class="label-green"><%= t ".approved" %></span>
                <% else %>
                  <span class="label-red"><%= t ".canceled" %></span>
                <% end %>
              </td>
              <td class="width-20">
                <%= link_to edit_admin_order_path(order) do %>
                  <i class="fa fa-lg fa-pencil-square-o"></i>
                <% end %>
              </td>
              <td class="width-20">
                <%= link_to admin_order_path(order), method: :delete,
                  data: {confirm: t("button.delete_warning")} do %>
                  <i class="fa fa-lg fa-times"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/orders/_order_info.html.erb
<h3 class="title"><%= t "admin_order.order_confirm" %></h3>
<table dir="ltr" class="default-dg-table">
  <tbody id="combo_dish">
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin.orders.order.code" %></b>
    </td>
    <td class="default_dg_td dg-left"><%= order.code %></td>
    <div class="hidden order-id"><%= order.id %></div>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin.orders.form.guest_name" %></b>
    </td>
    <td class="default_dg_td dg-left"><%= order.guest.name %></td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin_order.phone_num" %></b>
    </td>
    <td class="default_dg_td dg-left"><%= order.guest.phone_num %></td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin_order.email" %></b>
    </td>
    <td class="default_dg_td dg-left"><%= order.guest.email %></td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin.orders.form.date" %></b>
    </td>
    <td class="default_dg_td dg-left">
      <%= order.day.in_time_zone(Settings.time_zone).strftime('%b %d %Y') %>
    </td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap"><b>From</b></td>
    <td class="default_dg_td dg-left">
      <% if order.time_in == 1 %>
        <%= t "select.em" %><% end %>
      <% if order.time_in == 2 %>
        <%= t "select.lm" %><% end %>
      <% if order.time_in == 3 %>
        <%= t "select.ea" %><% end %>
      <% if order.time_in == 4 %>
        <%= t "select.la" %><% end %>
      <% if order.time_in == 5 %>
        <%= t "select.ee" %><% end %>
      <% if order.time_in == 6 %>
        <%= t "select.le" %><% end %>
    </td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin_order.table_id" %></b>
    </td>
    <td class="default_dg_td dg-left">
      <%= order.table_id %>
    </td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin.orders.form.capacity" %></b>
    </td>
    <td class="default_dg_td dg-left">
      <%= order.capacity %>
    </td>
  </tr>
  <tr class="dg_tr" id="di_row_0">
    <td class="default_dg_td dg-left dg-nowrap">
      <b><%= t "admin.orders.order.discount" %></b>
    </td>
    <td class="default_dg_td dg-left dg-nowrap">
      <%= order.discount %>%<br>
    </td>
  </tr>
  </tbody>
</table>
<br>
<div class="col-xs-12 text-center">
  <%= link_to t("admin.orders.edit.title"), edit_admin_order_path(order),
    class:"pj-button" %>
</div>

app/views/admin/orders/_order_item.html.erb
<thead>
<tr>
  <th><%= t "admin_order.product" %></th>
  <th><%= t "admin_order.type" %></th>
  <th><%= t "admin_order.original_price" %></th>
  <th><%= t "admin_order.quantity" %></th>
  <th><%= t "admin.combos.combo.discount" %></th>
  <th><%= t "admin_order.subtotal" %></th>
  <th colspan="2" class="text-center"><%= t "admin.orders.order.action" %></th>
</tr>
</thead>
<tbody>
<% order.order_dishes.each do |order_dish| %>
  <tr>
    <td class="total">
      <strong><%= link_to order_dish.dish.name,
        dish_path(order_dish.dish_id) %></strong>
    </td>
    <td class="total"><%= t "dishes.show.name" %></td>
    <td class="total">
      <%= number_to_currency order_dish.dish.price %>
    </td>
    <td class="total">
      <%= order_dish.quantity %>
    </td>
    <td class="total">0%</td>
    <td class="total">
      <%= number_to_currency order_dish.total_price %>
    </td>
    <td class="total width-10 text-center">
      <%= link_to edit_admin_order_order_dish_path(order,
        order_dish) do %>
        <i class="fa fa-lg fa-pencil-square-o"></i>
      <% end %>
    </td>
    <td class="total width-10 text-center">
      <%= link_to admin_order_order_dish_path(order,
        order_dish), method: :delete,
        data: { confirm: t("button.delete_warning") } do %>
        <i class="fa fa-lg fa-times"></i>
      <% end %>
    </td>
  </tr>
<% end %>
</tbody>
<tbody>
<% order.order_combos.each do |order_combo| %>
  <tr>
    <td class="total">
      <strong><%= link_to order_combo.combo.name,
        combo_path(order_combo.combo_id) %></strong>
    </td>
    <td class="total"><%= t "home.combo" %></td>
    <td class="total">
      <%= number_to_currency order_combo.combo.subtotal %>
    </td>
    <td class="total">
      <%= order_combo.quantity %>
    </td>
    <td class="total">
      <%= order_combo.combo.discount %>%
    </td>
    <td class="total">
      <%= number_to_currency order_combo.total_price %>
    </td>
    <td class="total width-10 text-center">
      <%= link_to edit_admin_order_order_combo_path(order,
        order_combo) do %>
        <i class="fa fa-lg fa-pencil-square-o"></i>
      <% end %>
    </td>
    <td class="total width-10 text-center">
      <%= link_to admin_order_order_combo_path(order, order_combo),
        method: :delete, data: { confirm: t("button.delete_warning") } do %>
        <i class="fa fa-lg fa-times"></i>
      <% end %>
    </td>
  </tr>
<% end %>
</tbody>
<tbody id="new-dish-row">

</tbody>
<tbody>
  <tr>
    <td class="btn-add-dish-row">
      <h4 class="dp-inline">
        <div class="btn btn-add-dish" id="btn-add-dish">
          <%= t "admin_order.add_dish" %></div>
       </h4>
      <h4 class="dp-inline">
        <div class="btn btn-add-dish" id="btn-add-combo">
          <%= t "admin_order.add_combo" %></div>
      </h4>
      <td colspan="6"></td>
      <td>
        <h4 class="dp-inline">
          <div class="btn btn-add-dish" id="btn-save-order">
            <%= t "order_detail.save" %></div>
        </h4>
      </td>
    </td>
  </tr>
</tbody>

app/views/admin/orders/edit.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-md-offset-1 col-md-10">
    <h1><%= t ".title" %></h1><br>
    <div class="bloc col-xs-12">
      <div class="form-dish form-order">
        <%= render "form", order: @order %>
      </div>
    </div>
  </div>
</section>

app/views/admin/orders/index.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-xs-12">
    <h1><%= t ".title" %></h1>
    <br>
    <div class="bloc col-xs-12">
      <div id="orders" class="search-form col-xs-12">
        <%= render "order", order: @orders_support, tables: @tables %>
      </div>
    </div>
  </div>
</section>

app/views/admin/orders/index.js.erb
$('#orders').html('<%= j render "order", order: @orders_support %>');
$('#pagination').html('<%= j paginate(@orders_support.orders_search,
  remote: true).to_s %>');

app/views/admin/orders/new.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-md-offset-1 col-md-10">
    <h1><%= t ".title" %></h1><br>
    <div class="bloc col-xs-12">
      <div class="form-dish form-order">
        <%= render "form", order: @order %>
      </div>
    </div>
  </div>
</section>

app/views/admin/orders/show.html.erb
<section class="section admin-site order-admin">
  <br><br>
  <div class="col-sm-10 col-sm-offset-1">
    <h1><%= t ".title" %></h1><br><br>
    <div class="bloc">
      <br>
      <%= render "order_info", order: @order %>
      <br><br>
      <h3 class="title order-item"><%= t "order.order_items" %> <span></span></h3>
      <br><br>
      <table class="items-table">
        <%= render "order_item", order: @order %>
        <tfoot>
        <tr>
          <td colspan="2" class="foot">
            <%= t "admin_order.original_price" %>
          </td>
          <td colspan="1" class="head">
            <%= number_to_currency @order.original_price %>
          </td>
          <td colspan="3" class="foot">
            <%= t "admin_order.total_notdiscount" %>
          </td>
          <td class="foot uk-text-left foot" colspan="3">
            <%= number_to_currency @order.subtotal %>
          </td>
        </tr>
        <tr>
          <td colspan="3" class="foot"></td>
          <td colspan="2" class="foot">
            <div class="btn btn-add-dish btn-voucher">
              <%= t "admin_order.voucher_add" %>
            </div>
          </td>
          <td colspan="1" class="foot">
            <%= t "admin_order.voucher_discount" %></td>
          <td class="foot" colspan="3" id="order-discount">
            <%= @order.discount %>%
          </td>
        </tr>
        <tr>
          <td class="total-price" colspan="6" align="right">
            <strong><%= t "admin_order.total" %></strong>
          </td>
          <td class="total-price" colspan="3" id="order-total" align="right">
            <strong>
              <%= number_to_currency (@order.subtotal * (100 -
                @order.discount))/100 %>
            </strong>
          </td>
        </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <%= render "modal", order: @order, discount: @support %>
  <%= render "modal_save_order" %>
</section>