config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resource :admin, only: [:show, :edit, :update]
  resources :dishes
  resources :orders, only: [:show, :index, :create]
  get "/cart", to: "orders#show"
  resources :order_dishes, only: [:create, :update, :destroy]
  resources :tables
  resources :guests
  resources :order_combos, only: [:create, :update, :destroy]
  resources :combos, only: [:index, :show]
  namespace :admin do
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :combos do
      resources :dishes
    end
    resources :orders do
      resources :order_dishes
      resources :order_combos
    end
    resources :discount_codes
    resources :users
  end
end

app/models/combo.rb
class Combo < ApplicationRecord
  has_many :combo_dishes
  has_many :dishes, through: :combo_dishes, dependent: :destroy
  has_many :order_combos

  validates :name, presence: true
  validates :discount, presence: true, numericality: {greater_than: 0}

  scope :popular_combos, ->{joins(:order_combos).group("combos.id")
    .order("count(combos.id) desc").limit(10)}

  def subtotal
    combo_dishes.map{|combo_dish| (combo_dish.dish.price)}.sum
  end

  def price
    (subtotal * (100 - discount)) / 100
  end
end

app/models/supports/combo.rb
class Supports::Combo
  attr_reader :combos

  def initialize arg
    @combos = arg
  end

  def combos
    @combos[:combo]
  end

  def combos_search
    search.result.page(@combos[:param][:page]).per_page Settings.limit
  end

  def search
    search = Combo.ransack @combos[:param][:q]
    search.sorts = %w(created_at desc name discount) if search.sorts.empty?
    search
  end
end

app/controllers/admin/combos_controller.rb
class Admin
  class CombosController < ApplicationController
    before_action :logged_in_admin
    before_action :find_combo, except: [:index, :new, :create]
    before_action :load_dishes, only: [:new, :edit]

    def index
      @combos = Supports::Combo.new combo: Combo.all, param: params
    end

    def new
      @combo = Combo.new
    end

    def create
      @combo = Combo.new combo_params
      if @combo.save
        flash[:success] = t "flash.combo.create_success"
        redirect_to admin_combo_path @combo
      else
        render :new
      end
    end

    def show
      @combo = Combo.includes(:dishes).find_by id: params[:id]
      @categories = Category.all
    end

    def edit
    end

    def update
      if @combo.update_attributes combo_params
        flash[:success] = t "flash.combo.update_success"
        redirect_to admin_combo_path @combo
      else
        redirect_to edit_admin_combo_path
      end
    end

    def destroy
      if @combo.destroy
        flash[:success] = t "flash.combo.destroy_success"
      else
        flash[:danger] = t "flash.combo.destroy_fail"
      end
      respond_to do |format|
        format.html{redirect_to :back}
        format.json{head :no_content}
      end
    end

    private
    def combo_params
      params.require(:combo).permit :name, :discount,
        :description, :image, dish_ids: []
    end

    def find_combo
      @combo = Combo.find_by id: params[:id]
      unless @combo
        flash[:danger] = t "flash.combo.find_fail"
        redirect_to admin_combos_path
      end
    end

    def load_dishes
      @dishes = Dish.all
    end
  end
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :find_combo, only: :show

  def index
    @combo_support = Supports::Combo.new combo: Combo.all, param: params
  end

  def show
    @order_combo = current_order.order_combos.new
  end

  private
  def find_combo
    @combo = Combo.find_by id: params[:id]
    unless @combo
      flash[:danger] = t "flash.combo.find_fail"
      redirect_to combos_path
    end
  end
end

app/views/admin/combos/_combo.html.erb
<%= search_form_for [:admin, combos.search], remote: true, method: :get do |f| %>
  <div class="input-group input-group-lg col-sm-12">
    <div class="col-sm-3 add">
      <%= link_to t("admin.combos.index.add_combo_button"),
        new_admin_combo_path, class: "btn btn-primary" %>
    </div>
    <div class="col-sm-9">
      <%= f.text_field :name_or_description_cont, class: "pj-form-field w180",
        placeholder: t(".input_keyword"), id: "searchinput" %>
      <span id="searchclear" class="form-control-clear glyphicon
        glyphicon-remove form-control-feedback">
      </span>
      <%= f.submit  t(".search"), class: "btn btn-info search-combo-button" %>
    </div>
  </div>
  <div id="admin-combos-pagination" class="apple-pagination">
    <%= paginate combos.combos_search, remote: true %>
  </div>
  <table class="default-dg-table">
    <tbody>
      <tr class="dg_tr" id="di_row_">
        <th class="default_dg_th dg-left dg-nowrap dg1">
          <%= sort_link combos.search, :id, t(".order"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="default_dg_th dg-center dg-nowrap dg2" colspan="2">
          <%= sort_link combos.search, :name, t(".name"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="default_dg_th dg-center dg-nowrap dg3">
          <%= sort_link combos.search, :discount, t(".discount"), {},
            {remote: true, method: :get} %>
        </th>
        <th class="default_dg_th dg-center dg-nowrap dg4" colspan="2">
          <%= t "Opition" %>
        </th>
      </tr>
      <% if combos.combos_search.any? %>
        <% combos.combos_search.each do |combo| %>
          <tr class="dg_tr" id="di_row_0">
            <td class="default_dg_td dg-left dg-nowrap dg1">
              <%= combo.id %>
            </td>
            <td class="default_dg_td dg-left dg-nowrap img">
              <%= image_tag combo.image %>
            </td>
            <td class="default_dg_td dg-left dg-nowrap dg2">
              <%= link_to combo.name, admin_combo_path(combo) %>
            </td>
            <td class="default_dg_td dg-center dg-nowrap dg3">
              <%= combo.discount %>%
            </td>
            <td class="default_dg_td dg-right dg-nowrap">
              <%= link_to edit_admin_combo_path(combo) do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
            </td>
            <td class="default_dg_td dg-left dg-nowrap img">
              <%= link_to admin_combo_path(combo), method: :delete,
                data: {confirm: t("button.delete_warning")} do %>
                <i class="fa fa-times" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
<% end %>

app/views/admin/combos/_form.html.erb
<%= form_for [:admin, combo] do |f| %>
  <%= f.label :name, t("admin.combos.edit.name"), class:"form-label" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :description, t("admin.combos.edit.description"), class:"form-label" %>
  <%= f.text_area :description, class: "form-control" %>
  <%= f.label :discount, t("admin.combos.edit.discount"), class:"form-label" %>
  <%= f.number_field :discount, class: "form-control", min: 0 %>
  <%= f.label :image, t("admin.combos.edit.image"), class:"form-label" %>
  <%= f.text_area :image, class: "form-control" %>
  <%= f.label :dishes, t(".dishes"), class:"form-label" %>
  <div class="col-xs-12">
  <% dishes.each do |dish| %>
    <div class="col-xs-6 col-sm-4 choose">
      <%= check_box_tag "combo[dish_ids][]", dish.id,
        combo.dishes.include?(dish) %>
      <%= label_tag :dish_ids, dish.name %>
    </div>
  <% end %>
  </div>
  <div class="col-xs-12 text-center">
  <% if combo.new_record? %>
    <%= f.submit class: "btn btn-primary" %>
    <%= f.submit t("button.clear"), type: :reset,
        class: "btn btn-danger" %>
  <% else %>
    <%= f.submit class: "btn btn-success" %>
    <%= f.submit t("button.clear"), type: :reset,
      class: "btn btn-danger" %>
  <% end %>
  </div>
<% end %>

app/views/admin/combos/edit.html.erb
<section class="section admin-site">
  <br>
  <br>
  <div class="col-sm-12 col-md-offset-1 col-md-10">
    <h1><%= t ".title" %></h1>
    <br>
    <div class="bloc col-xs-12">
      <div class="form-dish">
        <%= render "form", combo: @combo, dishes: @dishes %>
      </div>
    </div>
  </div>
</section>

app/views/admin/combos/index.html.erb
<section class="section admin-site">
  <br>
  <br>
  <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <h1><%= t ".title" %></h1>
    <div class="bloc col-xs-12">
      <div id="admin-combos" class="search-form">
        <%= render "combo", combos: @combos %>
      </div>
    </div>
  </div>
</section>

app/views/admin/combos/index.js.erb
$('#admin-combos').html('<%= j render "combo", combos: @combos,
  categories: @categories %>');
$('#admin-combos-pagination')
  .html('<%= j paginate(@combos.combos_search, remote: true).to_s %>');

app/views/admin/combos/new.html.erb
<section class="section admin-site">
  <br>
  <br>
  <div class="col-sm-12 col-md-10 col-md-offset-1">
    <h1><%= t ".title" %></h1><br>
    <% flash.each do |key, value| %>
      <div class="flash-message <%= key %>">
        <%= value %>
      </div>
    <% end %>
    <div class="bloc col-xs-12">
      <div class="form-dish">
        <%= render "form", combo: @combo, dishes: @dishes %>
      </div>
    </div>
  </div>
</section>

app/views/admin/combos/show.html.erb
<section class="section admin-site">
  <br>
  <br>
  <h1><%= t ".title" %></h1>
  <div class="col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="bloc">
      <table dir="ltr" class="default-dg-table">
        <tbody>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg-left dg-nowrap"><b><%= t ".name" %></b></td>
          <td class="default_dg_td dg-left"><%= @combo.name %></td>
        </tr>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg-left dg-nowrap"><b><%= t ".description" %></b></td>
          <td class="default_dg_td dg-left" colspan="2"><%= @combo.description %></td>
        </tr>
        </tbody>
      </table>
      <br>
      <h2><%= t ".dishes" %></h2>
      <table dir="ltr" class="default-dg-table">
        <tbody id="combo_dish">
        <tr class="dg_tr" style="" id="di_row_">
          <th class="default_dg_th dg-center dg-nowrap">
            <%= t ".no" %>
          </th>
          <th class="default_dg_th dg-left dg-nowrap" colspan="2">
            <%= t ".dish" %>
          </th>
          <th class="default_dg_th dg-center dg-nowrap">
            <%= t ".category" %>
          </th>
          <th class="default_dg_th dg-center dg-nowrap">
            <%= t ".opition" %>
          </th>
        </tr>
        <% @combo.dishes.each do |f| %>
          <tr class="dg_tr" id="di_row_0">
            <td class="default_dg_td dg-center dg-nowrap">
              <%= f.id %>
            </td>
            <td class="default_dg_td dg-left dg-nowrap" colspan="2">
              <%= link_to f.name, admin_dish_path(f) %>
            </td>
            <td class="default_dg_td dg-center dg-nowrap">
              <% @categories.each do |category| %>
                <% if f.categories.include? category %>
                  <% if category != f.categories.last %>
                    <%= link_to category.name, admin_category_path(category) %>,
                  <% else %>
                    <%= link_to category.name, admin_category_path(category) %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td class="default_dg_td dg-center dg-nowrap">
              <%= link_to t("button.delete"),
                admin_combo_dish_path(@combo.id, f.id),
                method: :delete, data: {confirm: t("button.delete_warning")} %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <br><br>
      <div class="col-sm-12 edit-combo-button">
        <%= link_to t(".edit_combo_button"), edit_admin_combo_path(@combo),
          class: "btn btn-primary col-md-2 col-md-offset-5 back" %>
        <%= link_to t("button.cancel"), :back,
          class: "btn btn-link btn-lg pull-right" %>
      </div>
    </div>
  </div>
</section>