config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resource :admin, only: [:show, :edit, :update]
  resources :dishes
  resources :orders, only: [:show, :index, :create]
  get "/cart", to: "orders#show"
  resources :order_dishes, only: [:create, :update, :destroy]
  resources :tables
  resources :guests
  resources :order_combos, only: [:create, :update, :destroy]
  resources :combos, only: [:index, :show]
  namespace :admin do
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :combos do
      resources :dishes
    end
    resources :orders do
      resources :order_dishes
      resources :order_combos
    end
    resources :discount_codes
    resources :users
  end
end

app/models/discount_code.rb
class DiscountCode < ApplicationRecord
  include Encode
  after_save :generate_code
end

app/models/supports/discount_code.rb
class Supports:: DiscountCode
  attr_reader :discount_codes

  def initialize arg
    @discounts = arg
  end

  def discounts
    @discounts[:discount]
  end

  def discounts_search
    search.result.page(@discounts[:param][:page]).per_page Settings.discount
  end

  def search
    search = DiscountCode.ransack @discounts[:param][:q]
    search.sorts = %w(code discount status) if search.sorts.empty?
    search
  end
end

app/controllers/admin/discount_codes_controller.rb
class Admin
  class DiscountCodesController < ApplicationController
    before_action :load_support

    def index
    end

    def create
      quantity = params[:quantity].to_i
      quantity.times do
        DiscountCode.new.update_attributes discount_params
      end
      link = "_item_discount_code"
      respond_to do |f|
        f.html{render link, layout: false, locals: {support: @support}}
      end
    end

    def update
      discount = find_discount_by_id
      unless discount.update_attributes discount_params
        flash[:danger] = t "admin_order.something_wrong"
      end
      link = "_item_discount_code"
      respond_to do |f|
        f.html{render link, layout: false, locals: {support: @support}}
      end
    end

    def destroy
      discount = find_discount_by_id
      if discount && discount.destroy
        redirect_to :back
      else
        flash[:danger] = t "admin_order.something_wrong"
      end
    end

    private
    def discount_params
      params.require(:discount_code).permit :discount, :status
    end

    def load_support
      @support = Supports::DiscountCode.new discount: DiscountCode.all,
        param: params
    end

    def find_discount_by_id
      discount = DiscountCode.find_by id: params[:id]
      if discount
        discount
      else
        flash[:danger] = t "admin_order.something_wrong"
      end
    end
  end
end

app/views/admin/discount_codes/_item_discount_code.html.erb
<div id="table-discount-code">
  <table class="default-dg-table table-discount-code">
    <tbody>
    <tr class="dg_tr" id="di_row_">
      <th class="default_dg_th dg-left dg-nowrap dg1">
        <%= sort_link support.search, :id, t(".order"), {},
          {remote: true, method: :get} %>
      </th>
      <th class="default_dg_th dg-center dg-nowrap dg2">
        <%= sort_link support.search, :code, t(".code"), {},
          {remote: true, method: :get} %>
      </th>
      <th class="default_dg_th dg-center dg-nowrap dg3">
        <%= sort_link support.search, :discount, t(".discount"), {},
          {remote: true, method: :get} %>
      </th>
      <th class="default_dg_th dg-center dg-nowrap dg3">
        <%= sort_link support.search, :status, t(".status"), {},
          {remote: true, method: :get} %>
      </th>
      <th class="default_dg_th dg-center dg-nowrap dg4" colspan="2">
        <%= t ".option" %>
      </th>
    </tr>
    <%= render "modal_edit" %>
    <% if support.discounts_search.any? %>
      <% support.discounts_search.each do |discount| %>
        <tr class="dg_tr" id="di_row_0">
          <td class="default_dg_td dg-left dg-nowrap dg1">
            <%= discount.id %>
          </td>
          <td class="default_dg_td dg-center dg-nowrap dg2
            discount-code<%= discount.id %>"><%= discount.code %></td>
          <td class="default_dg_td dg-center dg-nowrap dg3
            discount<%= discount.id %>"><%= discount.discount %></td>
          <td class="default_dg_td dg-center dg-nowrap dg3
            discount-status<%= discount.id %>"><%= discount.status %></td>
          <td class="default_dg_td dg-right dg-nowrap">
              <i class="fa fa-pencil-square-o" aria-hidden="true"
                id="btn-edit-discount" data="<%= discount.id %>"></i>
          </td>
          <td class="default_dg_td dg-left dg-nowrap img">
            <%= link_to admin_discount_code_path(discount), method: :delete,
              data: {confirm: t("button.delete_warning")} do %>
              <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/discount_codes/_modal_edit.erb
<div id="edit-discount-modal" class="modal">
  <div class="modal-content modal-sm">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2 class="text-center"><%= t ".edit_discount" %></h2>
    </div>
    <div class="modal-body">
      <div class="modal-form">
        <%= form_for :discount do |f| %>
          <%= f.hidden_field :id, id: "discount_id_field" %>
          <%= f.label :discount %>
          <%= f.number_field :discount,
            class: "form-control-discount", id: "discount_field" %>
          <%= f.label :status %>
          <%= f.select :status, ([t("select.available"), t("select.used")]),
           class: "form-control-discount", id: "discount_status" %>
        <% end %>
        <div class="btn btn-add-dish btn-save-modal">
          <%= t ".save" %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>

app/views/admin/discount_codes/index.html.erb
<section class="discount-screen">
  <div class="container">
    <div class="row">
      <div class="view-part col-sm-7">
        <br>
        <div class="row">
          <h3 class="col-sm-3"><%= t "discount.all" %></h3>
          <div class="col-sm-9 text-small">
            <%= search_form_for @support.search, url: admin_discount_codes_path,
              remote: true do |f| %>
              <div class="dp-inline">
                <%= f.text_field :code_cont,
                  class: "search-discount dp-inline",
                  placeholder: t("discount.input"), id: "searchinput" %>
                <span id="searchclear" class="glyphicon
                  glyphicon-remove-circle dp-inline close-circle-button"></span>
                <span class="input-group-btn dp-inline">
                  <%= f.submit t("admin.search"), class: "btn btn-add-dish
                    btn-search-discount btn-shadow" %>
                </span>
                <%= f.number_field :discount_eq, class: "pj-form-field w150",
                  placeholder: "Discount", min: 1 %>
                <%= f.select :status_cont,
                  [t("select.available"), t("select.used")],
                  {include_blank: t(".choose_status"),
                  selected: params[:q] ? params[:q][:status_cont] : ''},
                  class: "btn btn-default" %>
              </div>
            <% end %>
          </div>
        </div>
        <%= render "item_discount_code", support: @support %>
        <div id="discount-pagination" class="apple-pagination">
          <%= paginate @support.discounts_search, remote: true %>
        </div>
        <div id="counter" class="pagination-count text-center counter">
          <%= page_entries_info @support.discounts_search, remote: true %>
        </div>
      </div>
      <div class="view-part col-sm-4 half-view">
        <br>
        <h3 class="col-sm-12"><%= t "discount.generate" %></h3>
        <div class="row">
          <table class="generate-code dp-inline">
            <thead>
              <th><%= t ".discount" %></th>
              <th><%= t ".quantity" %></th>
              <th colspan="4" class="code-status-col">
                <%= t ".code_status" %>
              </th>
              <th></th>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%= number_field_tag "new_code_discount", 0,
                    {class: "quantity-in-discount", min: 0, include_blank: 0} %>
                </td>
                <td>
                  <%= number_field_tag "new_code_quantity", 0,
                    {class: "quantity-in-discount", min: 0, include_blank: 0} %>
                </td>
                <td colspan="4">
                  <%= select_tag "new_code_status", options_for_select([
                    t("select.available"), t("select.used")]),
                    {class: "quantity-in-discount"} %>
                </td>
                <td>
                  <div class="dp-inline btn btn-add-dish btn-generate btn-shadow"
                       id="btn-generate-code">
                    <%= t ".generate" %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>

        </div>
        <div class="generated-code">
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/discount_codes/index.js.erb
$('#discount-pagination').html('<%= j paginate(@support.discounts_search,
  remote: true).to_s %>');
$('.default-dg-table').html('<%= j render "item_discount_code",
  support: @support %>');