config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resource :admin, only: [:show, :edit, :update]
  resources :dishes
  resources :orders, only: [:show, :index, :create]
  get "/cart", to: "orders#show"
  resources :order_dishes, only: [:create, :update, :destroy]
  resources :tables
  resources :guests
  resources :order_combos, only: [:create, :update, :destroy]
  resources :combos, only: [:index, :show]
  namespace :admin do
    resources :categories do
      resources :dishes
    end
    resources :dishes
    resources :combos do
      resources :dishes
    end
    resources :orders do
      resources :order_dishes
      resources :order_combos
    end
    resources :discount_codes
    resources :users
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_admin
  before_action :find_user, only: [:edit, :update, :destroy]

  def index
    @list_admin = Admin.all.page(params[:page]).per_page Settings.max_result
  end

  def new
    @admin = Admin.new
  end

  def create
    user = Admin.new new_params
    if user.save
      flash[:success] = t "admin.success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "admin_order.something_wrong"
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @user.update_attributes update_params
      flash[:success] = t "admin.success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "admin_order.something_wrong"
      redirect_to edit_admin_user_path @user
    end
  end

  def destroy
    if @user.id != current_admin.id && @user.destroy
      flash[:success] = t "admin.success"
    else
      flash[:danger] = t "admin_order.something_wrong"
    end
    redirect_to admin_users_path
  end

  private
  def find_user
    @user = Admin.find_by id: params[:id]

    return if @user
    flash[:danger] = t "admin.not_exist"
    redirect_to admin_users_path
  end

  def new_params
    params.require(:admin).permit :email, :password, :password_confirmation,
      :name, :admin_role
  end

  def update_params
    params.require(:admin).permit :admin_role
  end
end

app/views/admin/users/edit.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-xs-12">
    <h1><%= t "admin.admin_management" %></h1>
    <br>
    <div class="bloc col-xs-6 col-xs-offset-3">
      <h4><%= t "admin.change_role" %>: <%= @user.email %></h4>
      <h4><%= t "admin.current_role" %>:
        <span class="badge"><%= @user.role %></span>
      </h4>
      <%= form_for @user, url: admin_user_path(@user), method: :put do |f| %>
        <%= f.select :admin_role, Admin.roles_select,
          {include_blank: t("admin.roles")}, id:"role_field",
          class: "form-control", required: true %>
        <hr>
        <%= f.button t("admin.update"), class: "btn btn-primary center-block" %>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/users/index.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-xs-12">
    <h1><%= t "admin.admin_management" %></h1>
    <br>
    <div class="bloc col-xs-8 col-xs-offset-2">
      <h3>
        <%= link_to new_admin_user_path do %>
          <i class="fa fa-fw fa-plus"></i><%= t "admin_users.new_admin" %>
        <% end %>
      </h3>
      <table class="table table-hover">
        <thead>
        <tr>
          <th><%= t "admin.email" %></th>
          <th><%= t "admin.date_created" %></th>
          <th><%= t "admin.role" %></th>
          <th><%= t "admin.orders.order.action" %></th>
        </tr>
        </thead>
        <tbody>
        <% @list_admin.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <td><%= user.role %></td>
            <td>
              <%= link_to t("button.edit"), edit_admin_user_path(user) %> |
              <%= link_to t("button.delete"), admin_user_path(user),
                method: :delete, data: {confirm: t("button.delete_warning")},
                class: "text-danger" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @list_admin %>
    </div>
  </div>
</section>

app/views/admin/users/new.html.erb
<section class="section admin-site">
  <br><br>
  <div class="col-sm-12 col-xs-12">
    <div class="bloc col-xs-8 col-xs-offset-2">
      <hr>
      <h1 class="text-center"><%= t "admin_users.new_admin" %></h1>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
          <%= form_for @admin, url: admin_users_path do |f| %>
            <div class="col-sm-12">
              <%= f.label :email, class: "form-label" %>
              <%= f.email_field :email,
                class: "form-control form-group", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.label :name, class: "form-label" %>
              <%= f.text_field :name,
                class: "form-control form-group", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.label :role, class: "form-label" %>
              <%= f.select :admin_role, Admin.roles_select,
                {include_blank: t("admin.roles")}, id:"role_field",
                class: "form-control", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.label :password, class: "form-label" %>
              <%= f.password_field :password,
                class: "form-control form-group", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.label :password_confirmation, class: "form-label" %>
              <%= f.password_field :password_confirmation,
                class: "form-control form-group", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.button t("helpers.submit.category.create", {model: Admin}),
                class: "btn btn-primary center-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>